### ISSUE TITLE
Make the Scheduler nice-aware

### ISSUE THREAD

**Issue by benjamin-wirch** [Malc01m/CS537-p5#3]
#### Make the Scheduler `nice`-aware

The default scheduler of xv6 uses round-robin policy, which does not take the priority of each process into account. Since now a thread/process has a property of niceness, the scheduler should be aware of that. This means it should now prioritize processes and threads based on their niceness values.

Specifically, in every scheduling decision (tick), the scheduler must select the thread or process with the lowest niceness value to run next. This selection prioritizes tasks with higher importance.

If multiple threads or processes share the same lowest niceness value, the scheduler should revert to a round-robin approach for these tasks, ensuring fair CPU time distribution among them.

Ensure that the modified scheduler treats processes and threads identically, applying the same priority rules to both.

After accommodating niceness when scheduling, you may test your solution using `test_4` \~ `test_9`.

**Comment by Malc01m** [comment]
Working on this in same branch as #2

**Comment by Malc01m** [comment]
Closed by #6
